# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # Ignore the libraries which are pinned
      - dependency-name: "Microsoft.Bcl.AsyncInterfaces"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore.Relational"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: nuget
    directory: /samples/Helpdesk.Relational.Tests
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /samples/Helpdesk.Relational
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /samples/Helpdesk.Relational
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions.Database
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions.EntityFrameworkCore
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions.Marten
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions.Reading
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions.Writing
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Expressions
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/Common.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/Expressions.EntityFrameworkCore.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/Expressions.Marten.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/Expressions.Reading.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/Expressions.Tests
    schedule:
      interval: daily
